import { mutation } from "./_generated/server";

export const seedProducts = mutation({
  args: {},
  handler: async (ctx) => {
    // Check if products already exist
    const existing = await ctx.db.query("products").first();
    if (existing) {
      return { seeded: false, message: "Products already exist" };
    }

    const U1 = "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=600&q=80";
    const U2 = "https://images.unsplash.com/photo-1517466787929-bc90951d0974?w=600&q=80";
    const U3 = "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=600&q=80";
    const U4 = "https://images.unsplash.com/photo-1504639725590-34d0984388bd?w=600&q=80";
    const U5 = "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=600&q=80";
    const U6 = "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=600&q=80";

    const P = (id: number) => `https://picsum.photos/id/${id}/600/800`;

    const products = [
      {
        name: "Camisa Retrô Brasil 1970 — Home",
        slug: "camisa-retro-brasil-1970-home",
        club: "Seleção Brasileira",
        year: 1970,
        type: "home",
        category: "selecoes",
        country: "Brasil",
        description: "Reviva a glória do tri-campeonato mundial com esta réplica da camisa usada pela Seleção Brasileira na Copa do México de 1970.",
        history: "Em 1970, a Seleção Brasileira conquistou o tricampeonato mundial no México com um futebol que encantou o mundo. Liderada por Pelé, a equipe de Zagallo é considerada por muitos a melhor de todos os tempos.",
        price: 179.9,
        promotionalPrice: 149.9,
        isNew: false,
        isBestSeller: true,
        isPromotion: true,
        isPublished: true,
        isDraft: false,
        rating: 4.9,
        reviewCount: 156,
        competition: "Copa do Mundo FIFA 1970",
        legendaryPlayers: ["Pelé", "Jairzinho", "Rivelino", "Tostão", "Gérson"],
        tags: ["seleção brasileira", "1970", "copa do mundo", "tri-campeão", "pelé"],
        decade: 1970,
        images: [U1, U4, P(1)],
        variants: [
          { size: "P", sku: "BR1970-P", stock: 15 },
          { size: "M", sku: "BR1970-M", stock: 22 },
          { size: "G", sku: "BR1970-G", stock: 18 },
          { size: "GG", sku: "BR1970-GG", stock: 10 },
          { size: "XG", sku: "BR1970-XG", stock: 5 },
        ],
      },
      {
        name: "Camisa Retrô Brasil 1994 — Home",
        slug: "camisa-retro-brasil-1994-home",
        club: "Seleção Brasileira",
        year: 1994,
        type: "home",
        category: "selecoes",
        country: "Brasil",
        description: "A camisa do tetra-campeonato mundial. O Brasil conquistou o mundo nos Estados Unidos com esta camisa que marcou gerações.",
        price: 169.9,
        isNew: false,
        isBestSeller: true,
        isPromotion: false,
        isPublished: true,
        isDraft: false,
        rating: 4.8,
        reviewCount: 132,
        competition: "Copa do Mundo FIFA 1994",
        legendaryPlayers: ["Romário", "Bebeto", "Dunga", "Taffarel", "Mauro Silva"],
        tags: ["seleção brasileira", "1994", "copa do mundo", "tetra-campeão"],
        decade: 1990,
        images: [U4, U1, P(10)],
        variants: [
          { size: "P", sku: "BR1994-P", stock: 12 },
          { size: "M", sku: "BR1994-M", stock: 20 },
          { size: "G", sku: "BR1994-G", stock: 15 },
          { size: "GG", sku: "BR1994-GG", stock: 8 },
          { size: "XG", sku: "BR1994-XG", stock: 3 },
        ],
      },
      {
        name: "Camisa Retrô Brasil 2002 — Home",
        slug: "camisa-retro-brasil-2002-home",
        club: "Seleção Brasileira",
        year: 2002,
        type: "home",
        category: "selecoes",
        country: "Brasil",
        description: "A camisa do penta. O Brasil voltou a ser campeão mundial no Japão e Coreia com esta camisa icônica.",
        price: 179.9,
        promotionalPrice: 159.9,
        isNew: false,
        isBestSeller: true,
        isPromotion: true,
        isPublished: true,
        isDraft: false,
        rating: 4.9,
        reviewCount: 198,
        competition: "Copa do Mundo FIFA 2002",
        legendaryPlayers: ["Ronaldo", "Rivaldo", "Ronaldinho", "Cafu", "Roberto Carlos"],
        tags: ["seleção brasileira", "2002", "copa do mundo", "penta-campeão"],
        decade: 2000,
        images: [U6, U1, P(100)],
        variants: [
          { size: "P", sku: "BR2002-P", stock: 18 },
          { size: "M", sku: "BR2002-M", stock: 25 },
          { size: "G", sku: "BR2002-G", stock: 20 },
          { size: "GG", sku: "BR2002-GG", stock: 12 },
          { size: "XG", sku: "BR2002-XG", stock: 6 },
        ],
      },
      {
        name: "Camisa Retrô Flamengo 1981 — Home",
        slug: "camisa-retro-flamengo-1981-home",
        club: "Flamengo",
        year: 1981,
        type: "home",
        category: "brasil",
        country: "Brasil",
        description: "A camisa do Flamengo campeão mundial e da Libertadores de 1981. Listras rubro-negras que marcaram a era de ouro do Mengão.",
        history: "Em 1981, o Flamengo de Zico conquistou a América e o Mundo. A equipe rubro-negra encantou com futebol ofensivo e envolvente, derrotando o Liverpool na final do Mundial no Japão.",
        price: 169.9,
        promotionalPrice: 149.9,
        isNew: false,
        isBestSeller: true,
        isPromotion: true,
        isPublished: true,
        isDraft: false,
        rating: 4.9,
        reviewCount: 223,
        competition: "Libertadores 1981 / Mundial 1981",
        legendaryPlayers: ["Zico", "Júnior", "Adílio", "Leandro", "Nunes"],
        tags: ["flamengo", "1981", "libertadores", "mundial", "zico"],
        decade: 1980,
        images: [U2, U3, P(200)],
        variants: [
          { size: "P", sku: "FLA1981-P", stock: 20 },
          { size: "M", sku: "FLA1981-M", stock: 30 },
          { size: "G", sku: "FLA1981-G", stock: 25 },
          { size: "GG", sku: "FLA1981-GG", stock: 15 },
          { size: "XG", sku: "FLA1981-XG", stock: 8 },
        ],
      },
      {
        name: "Camisa Retrô Liverpool 1984 — Home",
        slug: "camisa-retro-liverpool-1984-home",
        club: "Liverpool",
        year: 1984,
        type: "home",
        category: "mundo",
        country: "Inglaterra",
        description: "O vermelho dos Reds que dominou a Europa nos anos 80.",
        history: "O Liverpool de 1984 conquistou a Europa sob o comando de Joe Fagan, derrotando a Roma na final da Taça dos Campeões Europeus.",
        price: 169.9,
        isNew: false,
        isBestSeller: true,
        isPromotion: false,
        isPublished: true,
        isDraft: false,
        rating: 4.7,
        reviewCount: 78,
        competition: "Taça dos Campeões Europeus 1984",
        legendaryPlayers: ["Ian Rush", "Kenny Dalglish", "Graeme Souness", "Alan Hansen"],
        tags: ["liverpool", "1984", "reds", "inglaterra"],
        decade: 1980,
        images: [U3, U2, P(300)],
        variants: [
          { size: "P", sku: "LIV1984-P", stock: 10 },
          { size: "M", sku: "LIV1984-M", stock: 18 },
          { size: "G", sku: "LIV1984-G", stock: 15 },
          { size: "GG", sku: "LIV1984-GG", stock: 8 },
          { size: "XG", sku: "LIV1984-XG", stock: 4 },
        ],
      },
      {
        name: "Camisa Retrô Manchester United 1999 — Home",
        slug: "camisa-retro-manchester-united-1999-home",
        club: "Manchester United",
        year: 1999,
        type: "home",
        category: "mundo",
        country: "Inglaterra",
        description: "O vermelho da tríplice coroa. O Manchester United de 1999 conquistou tudo.",
        price: 179.9,
        promotionalPrice: 159.9,
        isNew: false,
        isBestSeller: true,
        isPromotion: true,
        isPublished: true,
        isDraft: false,
        rating: 4.8,
        reviewCount: 145,
        competition: "Premier League / FA Cup / Champions League 1999",
        legendaryPlayers: ["Beckham", "Giggs", "Scholes", "Keane", "Solskjær"],
        tags: ["manchester united", "1999", "tríplice coroa", "inglaterra"],
        decade: 1990,
        images: [U5, U6, P(400)],
        variants: [
          { size: "P", sku: "MU1999-P", stock: 14 },
          { size: "M", sku: "MU1999-M", stock: 22 },
          { size: "G", sku: "MU1999-G", stock: 18 },
          { size: "GG", sku: "MU1999-GG", stock: 10 },
          { size: "XG", sku: "MU1999-XG", stock: 5 },
        ],
      },
      {
        name: "Camisa Retrô Argentina 1986 — Home",
        slug: "camisa-retro-argentina-1986-home",
        club: "Seleção Argentina",
        year: 1986,
        type: "home",
        category: "selecoes",
        country: "Argentina",
        description: "A camisa celeste e branca da Argentina bicampeã mundial.",
        history: "A Copa de 1986 foi de Diego Maradona. O gênio argentino marcou dois dos gols mais famosos da história: 'A Mão de Deus' e 'O Gol do Século'.",
        price: 179.9,
        isNew: false,
        isBestSeller: true,
        isPromotion: false,
        isPublished: true,
        isDraft: false,
        rating: 4.9,
        reviewCount: 167,
        competition: "Copa do Mundo FIFA 1986",
        legendaryPlayers: ["Maradona", "Valdano", "Burruchaga", "Ruggeri"],
        tags: ["argentina", "1986", "copa do mundo", "maradona"],
        decade: 1980,
        images: [P(500), U4, P(20)],
        variants: [
          { size: "P", sku: "ARG1986-P", stock: 12 },
          { size: "M", sku: "ARG1986-M", stock: 20 },
          { size: "G", sku: "ARG1986-G", stock: 16 },
          { size: "GG", sku: "ARG1986-GG", stock: 8 },
          { size: "XG", sku: "ARG1986-XG", stock: 4 },
        ],
      },
      {
        name: "Camisa Retrô Real Madrid 2002 — Home",
        slug: "camisa-retro-real-madrid-2002-home",
        club: "Real Madrid",
        year: 2002,
        type: "home",
        category: "mundo",
        country: "Espanha",
        description: "O branco imaculado do Real Madrid campeão europeu.",
        history: "Na final de 2002, Zidane marcou um dos gols mais bonitos da história da Champions League com um voleio espetacular.",
        price: 179.9,
        isNew: false,
        isBestSeller: true,
        isPromotion: false,
        isPublished: true,
        isDraft: false,
        rating: 4.8,
        reviewCount: 134,
        competition: "Champions League 2002",
        legendaryPlayers: ["Zidane", "Raúl", "Figo", "Roberto Carlos", "Ronaldo"],
        tags: ["real madrid", "2002", "champions", "zidane", "espanha"],
        decade: 2000,
        images: [P(600), U6, P(30)],
        variants: [
          { size: "P", sku: "RM2002-P", stock: 10 },
          { size: "M", sku: "RM2002-M", stock: 18 },
          { size: "G", sku: "RM2002-G", stock: 14 },
          { size: "GG", sku: "RM2002-GG", stock: 7 },
          { size: "XG", sku: "RM2002-XG", stock: 3 },
        ],
      },
      {
        name: "Camisa Retrô Santos 1962 — Home",
        slug: "camisa-retro-santos-1962-home",
        club: "Santos",
        year: 1962,
        type: "home",
        category: "brasil",
        country: "Brasil",
        description: "A camisa do Santos bicampeão mundial. As listras pretas e brancas que Pelé eternizou.",
        price: 179.9,
        isNew: false,
        isBestSeller: true,
        isPromotion: false,
        isPublished: true,
        isDraft: false,
        rating: 4.7,
        reviewCount: 89,
        competition: "Libertadores 1962 / Mundial 1962",
        legendaryPlayers: ["Pelé", "Mengálvio", "Coutinho", "Pepe", "Zito"],
        tags: ["santos", "1962", "pelé", "libertadores", "mundial"],
        decade: 1960,
        images: [P(700), U2, P(40)],
        variants: [
          { size: "P", sku: "SAN1962-P", stock: 8 },
          { size: "M", sku: "SAN1962-M", stock: 15 },
          { size: "G", sku: "SAN1962-G", stock: 12 },
          { size: "GG", sku: "SAN1962-GG", stock: 6 },
          { size: "XG", sku: "SAN1962-XG", stock: 3 },
        ],
      },
      {
        name: "Camisa Retrô Milan 1989 — Home",
        slug: "camisa-retro-milan-1989-home",
        club: "Milan",
        year: 1989,
        type: "home",
        category: "mundo",
        country: "Itália",
        description: "O vermelho e preto do Milan imortal de Sacchi.",
        history: "O Milan de Arrigo Sacchi revolucionou o futebol com sua linha defensiva alta e marcação sob pressão.",
        price: 169.9,
        isNew: false,
        isBestSeller: false,
        isPromotion: false,
        isPublished: true,
        isDraft: false,
        rating: 4.7,
        reviewCount: 88,
        competition: "Champions League 1989",
        legendaryPlayers: ["Van Basten", "Gullit", "Rijkaard", "Baresi", "Maldini"],
        tags: ["milan", "1989", "itália", "champions", "sacchi"],
        decade: 1980,
        images: [P(800), U3, P(50)],
        variants: [
          { size: "P", sku: "MIL1989-P", stock: 8 },
          { size: "M", sku: "MIL1989-M", stock: 14 },
          { size: "G", sku: "MIL1989-G", stock: 12 },
          { size: "GG", sku: "MIL1989-GG", stock: 6 },
          { size: "XG", sku: "MIL1989-XG", stock: 3 },
        ],
      },
    ];

    for (const product of products) {
      const { images, variants, ...productData } = product;

      const productId = await ctx.db.insert("products", productData);

      for (let i = 0; i < images.length; i++) {
        await ctx.db.insert("productImages", {
          productId,
          url: images[i],
          order: i,
        });
      }

      for (const variant of variants) {
        await ctx.db.insert("productVariants", {
          productId,
          ...variant,
        });
      }
    }

    // Create site settings
    const settings = [
      { key: "storeName", value: "VesteRetro" },
      { key: "storeSlogan", value: "Vista a História." },
      { key: "whatsapp", value: "5511987516823" },
      { key: "maxInstallments", value: 12 },
      { key: "freeShippingThreshold", value: 299 },
      { key: "pixDiscount", value: 5 },
    ];

    for (const setting of settings) {
      await ctx.db.insert("siteSettings", setting);
    }

    return { seeded: true, count: products.length };
  },
});
